# Generated by Django 6.0.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usertwofactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefugeStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("oxygen", models.PositiveSmallIntegerField(default=84)),
                ("hygiene", models.PositiveSmallIntegerField(default=52)),
                ("radiation", models.PositiveSmallIntegerField(default=71)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
