# Generated by Django 6.0.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_refugestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalevent",
            name="agitation_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="containment_integrity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="estimated_impact",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="requires_shutdown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="sector",
            field=models.CharField(default="EXTERNAL", max_length=50),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="severity",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")],
                default="INFO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="externalevent",
            name="specimen_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
