# Generated by Django 6.0.2 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_externalevent_realistic_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="refugestatus",
            name="biomass_density",
            field=models.FloatField(default=38.0),
        ),
        migrations.AddField(
            model_name="refugestatus",
            name="melanin_index",
            field=models.PositiveSmallIntegerField(default=61),
        ),
        migrations.AddField(
            model_name="refugestatus",
            name="radiation_absorption_rate",
            field=models.FloatField(default=74.0),
        ),
        migrations.AddField(
            model_name="refugestatus",
            name="structural_infiltration_level",
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
